<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\StudentCertificates;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use File;
use PDF;

class CertificateAuditController extends Controller
{
    public function missingCertificates()
    {
        $certificates = StudentCertificates::with(['student.school', 'grade'])
            ->orderBy('id', 'desc')
            ->get();

        $missing = $certificates->filter(function ($cert) {
            $expectedPath = 'certificates/' . $cert->unique_id . '.pdf';

            // If pdf_path missing but file exists, fix record and exclude from missing.
            if (!$cert->pdf_path && File::exists(public_path($expectedPath))) {
                $cert->pdf_path = $expectedPath;
                $cert->save();
                return false;
            }

            if (!$cert->pdf_path) {
                return true;
            }

            return !File::exists(public_path($cert->pdf_path));
        });

        return view('backend.certificates.missing', [
            'missingCertificates' => $missing
        ]);
    }

    public function regenerateCertificate($id)
    {
        $certificate = StudentCertificates::with(['student.school', 'grade'])->findOrFail($id);

        if (!$certificate->student || !$certificate->grade) {
            return redirect()
                ->route('backend.certificates.missing')
                ->with('error', 'Certificate data is incomplete. Student or grade missing.');
        }

        // If a PDF already exists at the expected path, fix the record and exit.
        $expectedPath = 'certificates/' . $certificate->unique_id . '.pdf';
        if (!$certificate->pdf_path && File::exists(public_path($expectedPath))) {
            $certificate->pdf_path = $expectedPath;
            $certificate->save();
            return redirect()
                ->route('backend.certificates.missing')
                ->with('success', 'Certificate record fixed (PDF already exists).');
        }

        $path = $this->generateAndStoreCertificatePDF($certificate);
        if ($path && File::exists(public_path($path))) {
            return redirect()
                ->route('backend.certificates.missing')
                ->with('success', 'Certificate regenerated successfully.');
        }

        return redirect()
            ->route('backend.certificates.missing')
            ->with('error', 'Failed to regenerate certificate. Check logs for details.');
    }

    private function generateAndStoreCertificatePDF(StudentCertificates $certificate)
    {
        try {
            $student = $certificate->student;
            $grade = $certificate->grade;
            $school = $student ? $student->school : null;
            $schoolLogoPath = asset('asset/images/logo.png');

            if ($school && isset($school->school_logo)) {
                $logoPath = Storage::disk('tenant_uploads')->path($school->school_logo);
                if (File::exists($logoPath)) {
                    $schoolLogoPath = url('tenants/' . $school->school_logo);
                }
            }

            $pdf = PDF::loadView('certificates.studentcertificate', [
                'student' => $student,
                'grade' => $grade,
                'certificate' => $certificate,
                'custom_quote' => null,
                'schoolLogoPath' => $schoolLogoPath
            ]);

            $pdf->setPaper('A4', 'landscape');

            $filename = $certificate->unique_id . '.pdf';
            $path = 'certificates/' . $filename;
            $fullPath = public_path($path);
            $directory = dirname($fullPath);

            if (!File::exists($directory)) {
                File::makeDirectory($directory, 0755, true);
            }

            $pdf->save($fullPath);

            $certificate->pdf_path = $path;
            $certificate->save();

            Log::info('Certificate regenerated by admin', [
                'certificate_id' => $certificate->id,
                'pdf_path' => $path
            ]);

            return $path;
        } catch (\Exception $e) {
            Log::error('Failed to regenerate certificate by admin', [
                'certificate_id' => $certificate->id,
                'error' => $e->getMessage()
            ]);
            return null;
        }
    }
}
